<?php

if (!defined('__DIR__')) {define('__DIR__', dirname(__FILE__));}
require_once __DIR__ . '/user_wemove.admin.inc';


/**
 * Redirection (for users with campaigner role/ so logged in):
 * to edit user profile page 
 * from every others user profile pages
 */
function user_wemove_init(){
  global $user;

  if(user_is_logged_in() && _checkCampaignerRole() && _checkUserPath()){
      drupal_goto('user/'.$user->uid.'/edit');
  }
}


/**
 * Customize the tabs on user profile pages (for users with campaigner role):
 * - Hide every tab with the link related with user profiles pages
 */
function user_wemove_menu_local_tasks_alter(&$data) {
   global $user;
   
   if(_checkCampaignerRole() && (current_path() === "user/".$user->uid."/edit")){

     foreach ($data['tabs'] as $key => $value) {
       foreach($value['output'] as $tab_index => $tab) {
         if (substr($tab['#link']['path'],0,6) === 'user/%') {
           unset($data['tabs'][0]['output'][$key]);
         }
       }
     }
  }
}


/**
 * Customize the user profile form (for users with campaigner role):
 * - Hide: 
 *   -- login control
 *   -- mail control
 *   -- status control
 *   -- roles control
 *   -- notify control
 *   -- picture control
 *   -- time control
 * - Change password desription
 */
function user_wemove_form_alter(&$form, &$form_state, $form_id) {
  if($form_id === 'user_profile_form' && _checkCampaignerRole()) {
   
    hide($form['account']['name']);
    hide($form['account']['mail']);
    hide($form['account']['status']);
    hide($form['account']['roles']);
    hide($form['account']['notify']);
    hide($form['picture']);
    
    unset($form['locale']);

    if(array_key_exists('account',$form) && array_key_exists('current_pass',$form['account'])) {
        $descr = str_replace(t('Enter your current password to change the <em class="placeholder">E-mail address</em> or <em class="placeholder">Password</em>'),t('Enter your current password to change the <em class="placeholder">Password</em>'),$form['account']['current_pass']['#description']);
        $form['account']['current_pass']['#description'] = $descr;
    }
  }
}

/**
 * Check if logged in user has campaigner role
 * configured in module configuration form
 *
 * Return: False/True 
 */
function _checkCampaignerRole() {
  global $user;
  $role_name = variable_get('user_wemove__ymu_user_role_name', NULL);

  $role = user_role_load_by_name($role_name);
  $rid = $role->rid;

  return (array_key_exists($rid,$user->roles));
}


/**
 * Check current path if it's related to user profile pages
 *
 * Return: False/True
 */
function _checkUserPath() {
  global $user;
  $path = current_path();
  $pathRegLength = strlen((string) $user->uid) + 5;

  return ($path === "user" ||
          $path === "user/".$user->uid ||
          $path === "user/".$user->uid."/view" ||
          $path === "user/".$user->uid."/edit/name_and_address");
}

